// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ParkeringsDataAPI.Models
{
    [Table("Parkeringsområde")]
    public partial class Parkeringsområde
    {
        public Parkeringsområde()
        {
            Logs = new HashSet<Log>();
            SpecielleParkeringsPladsers = new HashSet<SpecielleParkeringsPladser>();
        }

        [Key]
        public int Id { get; set; }
        public int Pladser { get; set; }
        public int OptagedePladser { get; set; }

        [InverseProperty(nameof(Log.Område))]
        public virtual ICollection<Log> Logs { get; set; }
        [InverseProperty(nameof(SpecielleParkeringsPladser.Område))]
        public virtual ICollection<SpecielleParkeringsPladser> SpecielleParkeringsPladsers { get; set; }
    }
}