// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ParkeringsDataAPI.Models
{
    public partial class ParkingDatum
    {
        [Key]
        public int Id { get; set; }
        public int? Total { get; set; }
        public int? Ledige { get; set; }
        public int? Optagede { get; set; }
    }
}