// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ParkeringsDataAPI.Models
{
    [Table("SpecielleParkeringsPladser")]
    public partial class SpecielleParkeringsPladser
    {
        [Key]
        public int OmrådeId { get; set; }
        [Key]
        public int ParkeringsType { get; set; }
        public int Pladser { get; set; }
        public int OptagedePladser { get; set; }

        [ForeignKey(nameof(OmrådeId))]
        [InverseProperty(nameof(Parkeringsområde.SpecielleParkeringsPladsers))]
        public virtual Parkeringsområde Område { get; set; }
    }
}